### ISSUE TITLE
Accessing resource with expired bearer token sometimes throws exceptions and/or returns different response 

### ISSUE THREAD

**Issue by saintcoder** [spring-projects/spring-cloud#10]
The issue is fully described at stackoverflow http://stackoverflow.com/questions/30735890/accessing-resource-with-expired-bearer-token-fails-with-500-http-code

Raising the request here as suggested by @dsyer at https://github.com/spring-projects/spring-security-oauth/issues/505

**Comment by dsyer** [comment]
This is the wrong repository. But I think the bug was fixed here: https://github.com/spring-cloud/spring-cloud-security/commit/7d3116286136e4fb29f22765b8e7fb045186d4b7
