### ISSUE TITLE
Dependency problem ?

### ISSUE THREAD

**Issue by maxiplay** [spring-projects/spring-cloud#15]
I went to http://start.spring.io/ and I have downloaded eureka server demo.

![image](https://cloud.githubusercontent.com/assets/8363127/13668049/5fcdcf8e-e6ba-11e5-879f-283e91ffbd47.png)

But When I try to mvn clean install I have the following error message 

Note : I recently cleared my local maven repository

Downloading: http://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-aws-dependencies/1.1.0.M2/spring-cloud-aws-dependencies-1.1.0.M2.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.example:demo:0.0.1-SNAPSHOT (C:\Utilisateurs\A555846\Documents\writeControl\workspace\demo\pom.xml) has 12 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-stream-dependencies:pom:1.0.0.M4 in central (http://repo.maven.apache.org/maven2) @ org.springframework.cloud:spring-cloud-dependencies:Brixton.M5, C:\Utilisateurs\A555846\.m2\repository\org\springf
ramework\cloud\spring-cloud-dependencies\Brixton.M5\spring-cloud-dependencies-Brixton.M5.pom, line 288, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-config-dependencies:pom:1.1.0.M5 in central (http://repo.maven.apache.org/maven2) @ org.springframework.cloud:spring-cloud-dependencies:Brixton.M5, C:\Utilisateurs\A555846\.m2\repository\org\springf
ramework\cloud\spring-cloud-dependencies\Brixton.M5\spring-cloud-dependencies-Brixton.M5.pom, line 295, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-consul-dependencies:pom:1.0.0.M6 in central (http://repo.maven.apache.org/maven2) @ org.springframework.cloud:spring-cloud-dependencies:Brixton.M5, C:\Utilisateurs\A555846\.m2\repository\org\springf
ramework\cloud\spring-cloud-dependencies\Brixton.M5\spring-cloud-dependencies-Brixton.M5.pom, line 302, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-netflix-dependencies:pom:1.1.0.M5 in central (http://repo.maven.apache.org/maven2) @ org.springframework.cloud:spring-cloud-dependencies:Brixton.M5, C:\Utilisateurs\A555846\.m2\repository\org\spring
framework\cloud\spring-cloud-dependencies\Brixton.M5\spring-cloud-dependencies-Brixton.M5.pom, line 309, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-sleuth-dependencies:pom:1.0.0.M5 in central (http://repo.maven.apache.org/maven2) @ org.springframework.cloud:spring-cloud-dependencies:Brixton.M5, C:\Utilisateurs\A555846\.m2\repository\org\springf
ramework\cloud\spring-cloud-dependencies\Brixton.M5\spring-cloud-dependencies-Brixton.M5.pom, line 316, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-zookeeper-dependencies:pom:1.0.0.M5 in central (http://repo.maven.apache.org/maven2) @ org.springframework.cloud:spring-cloud-dependencies:Brixton.M5, C:\Utilisateurs\A555846\.m2\repository\org\spri
ngframework\cloud\spring-cloud-dependencies\Brixton.M5\spring-cloud-dependencies-Brixton.M5.pom, line 323, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-cloudfoundry-dependencies:pom:1.0.0.M4 in central (http://repo.maven.apache.org/maven2) @ org.springframework.cloud:spring-cloud-dependencies:Brixton.M5, C:\Utilisateurs\A555846\.m2\repository\org\s
pringframework\cloud\spring-cloud-dependencies\Brixton.M5\spring-cloud-dependencies-Brixton.M5.pom, line 330, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-bus-dependencies:pom:1.1.0.M5 in central (http://repo.maven.apache.org/maven2) @ org.springframework.cloud:spring-cloud-dependencies:Brixton.M5, C:\Utilisateurs\A555846\.m2\repository\org\springfram
ework\cloud\spring-cloud-dependencies\Brixton.M5\spring-cloud-dependencies-Brixton.M5.pom, line 337, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-task-dependencies:pom:1.0.0.M1 in central (http://repo.maven.apache.org/maven2) @ org.springframework.cloud:spring-cloud-dependencies:Brixton.M5, C:\Utilisateurs\A555846\.m2\repository\org\springfra
mework\cloud\spring-cloud-dependencies\Brixton.M5\spring-cloud-dependencies-Brixton.M5.pom, line 344, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-cluster-dependencies:pom:1.0.0.M4 in central (http://repo.maven.apache.org/maven2) @ org.springframework.cloud:spring-cloud-dependencies:Brixton.M5, C:\Utilisateurs\A555846\.m2\repository\org\spring
framework\cloud\spring-cloud-dependencies\Brixton.M5\spring-cloud-dependencies-Brixton.M5.pom, line 351, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-aws-dependencies:pom:1.1.0.M2 in central (http://repo.maven.apache.org/maven2) @ org.springframework.cloud:spring-cloud-dependencies:Brixton.M5, C:\Utilisateurs\A555846\.m2\repository\org\springfram
ework\cloud\spring-cloud-dependencies\Brixton.M5\spring-cloud-dependencies-Brixton.M5.pom, line 358, column 16 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-eureka-server:jar is missing. @ line 27, column 15
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by maxiplay** [comment]
Note 

I can download other dependencies

Downloading: http://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-stream-dependencies/1.0.0.M4/spring-cloud-stream-dependencies-1.0.0.M4.pom
Downloading: http://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-config-dependencies/1.1.0.M5/spring-cloud-config-dependencies-1.1.0.M5.pom
Downloading: http://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-consul-dependencies/1.0.0.M6/spring-cloud-consul-dependencies-1.0.0.M6.pom
Downloading: http://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-netflix-dependencies/1.1.0.M5/spring-cloud-netflix-dependencies-1.1.0.M5.pom
Downloading: http://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-sleuth-dependencies/1.0.0.M5/spring-cloud-sleuth-dependencies-1.0.0.M5.pom
Downloading: http://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-zookeeper-dependencies/1.0.0.M5/spring-cloud-zookeeper-dependencies-1.0.0.M5.pom
Downloading: http://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-cloudfoundry-dependencies/1.0.0.M4/spring-cloud-cloudfoundry-dependencies-1.0.0.M4.pom
Downloading: http://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-bus-dependencies/1.1.0.M5/spring-cloud-bus-dependencies-1.1.0.M5.pom
Downloading: http://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-task-dependencies/1.0.0.M1/spring-cloud-task-dependencies-1.0.0.M1.pom
Downloading: http://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-cluster-dependencies/1.0.0.M4/spring-cloud-cluster-dependencies-1.0.0.M4.pom
Downloading: http://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-aws-dependencies/1.1.0.M2/spring-cloud-aws-dependencies-1.1.0.M2.pom

**Comment by spencergibb** [comment]
You absolutely are not able to download milestones from maven central. Does your company have a maven proxy or something? This is the wrong repo to use.

You should also use `./mvnw` to build.

If you feel I'm closing this in error, open an issue here https://github.com/spring-cloud/spring-cloud-starters/issues

**Comment by TonyLuo** [comment]
@maxiplay i have the same issue. have you fixed it?

**Comment by ryanjbaxter** [comment]
@TonyLuo I assume you dont have the same issue since you would most likely not be using this version of Spring Cloud.  If you are having issues downloading the dependencies for your project please open an issue in the link @spencergibb mentioned above.

**Comment by yakhyadabo** [comment]
I'm having the same issue. 
Did you find any solution?

**Comment by aurindo** [comment]
I'm having the same issue too.

**Comment by yakhyadabo** [comment]
It works for me when I've made the following changes in the POM : 
**Spring boot parent :** <version>1.5.10.RELEASE</version>
**Spring cloud  :** <spring-cloud.version>Edgware.SR2</spring-cloud.version>
