### ISSUE TITLE
Spring Cloud Config Server version change

### ISSUE THREAD

**Issue by SaltOfTheFlame** [spring-projects/spring-cloud#18]
Hello, dear spring cloud commiters

I have a project, running on spring boot 1.3.8 and Brixton.SR7
Question is, will it be right and, if not, is it safe and what can I expect if I am going to use Spring Cloud Config Server from Camden freshest releases ?
Does that worse the troubles, that could appear?

**Comment by ryanjbaxter** [comment]
@SaltOfTheFlame if your question is specifically related to Spring Cloud Config, I suggest you ask your question in that [project](https://github.com/spring-cloud/spring-cloud-config).
