### ISSUE TITLE
eurekaInstanceConfigBean creation issue

### ISSUE THREAD

**Issue by abhiroopghatak** [spring-projects/spring-cloud#26]
Error creating bean with name 'eurekaInstanceConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!

**Comment by ryanjbaxter** [comment]
Sounds like this issue belongs in the Spring Cloud Netflix project https://github.com/spring-cloud/spring-cloud-netflix.

Please open an issue there and provide a description of the problem including the stack trace and a sample that reproduces the problem.
