### ISSUE TITLE
Lost "mainApplicationClass" property while starting up using the "SpringBootServletInitializer" way

### ISSUE THREAD

**Issue by 391861737** [spring-projects/spring-cloud#28]
**knock knock**

I recently found that my customed `EvnProcessor#postProcessEnvironment` throws a `NullPointerException` when calling `application.getMainApplicationClass().getName()` when I deployed my web application in a tomcat server (in which application boots from `ServletContainerInitializer` under **Servlet 3.0** and invokes `SpringBootServletInitializer#onStartup` to initialize), but it works fine while I boot it using default springboot's main method.

As I traced, `org.springframework.cloud.bootstrap.BootstrapApplicationListener` listens on the `ApplicationEnvironmentPreparedEvent` and then build a different `SpringApplicationBuilder`(`#bootstrapServiceContext`) when creating the [Bootstrap Application Context](https://cloud.spring.io/spring-cloud-static/Finchley.SR1/single/spring-cloud.html#_the_bootstrap_application_context) where a new `SpringApplication` instance is created using it's constructor which deduces mainApplicationClass by searching `StackTraceElement`s for the "main" method (`org.springframework.boot.SpringApplication#deduceMainApplicationClass`).
That "main" method is unfortunately absence while booting inside a tomcat server using `ServletContainerInitializer`. Hence my customed `EvnProcessor#postProcessEnvironment`'s second argument `SpringApplication`  which deduces none mainApplicationClass produces a `NullPointerException`.

On the other hand, `SpringBootServletInitializer#createRootApplicationContext` explicitly set the mainApplicationClass by `builder.main(getClass())`. So, I thought it might make sense if the `org.springframework.cloud.bootstrap.BootstrapApplicationListener#bootstrapServiceContext`  behaves the same way `SpringBootServletInitializer#createRootApplicationContext` does when dealing with mainApplicationClass.
And the true mainApplicationClass is holded by `BootstrapApplicationListener#bootstrapServiceContext`'s second argument `SpringApplication application` while the newly created `SpringApplication` instance deduces none. It might be handy to pass it to the newly created `SpringApplication` instance.

After all, mainApplicationClass is really useful, and deploying in some web containers and booting from `ServletContainerInitializer` is somehow unavoidable.

**Comment by 391861737** [comment]
relevant versions are as follows:
> spring-cloud-context-2.0.0.RELEASE.jar
> spring-boot-2.0.3.RELEASE.jar

**Comment by ryanjbaxter** [comment]
This is the wrong repo for this issue, please open an issue here https://github.com/spring-cloud/spring-cloud-commons.  Also please provide a sample that reproduces the problem.

**Comment by 391861737** [comment]
> This is the wrong repo for this issue, please open an issue here https://github.com/spring-cloud/spring-cloud-commons. Also please provide a sample that reproduces the problem.

Thanks, and I've opened a same issue there, and a pull request as well. It's my first time doing this... There could have been something that I'm not aware of (and not good)... Is there any chance that I'm not going to be blamed on any of those? O, so does my English expression (It is not my mother tongue).
