### ISSUE TITLE
Spring cloud core - Pivotal cloud foundry issue

### ISSUE THREAD

**Issue by arumugham86** [spring-projects/spring-cloud#30]
Team, I am not sure where to raise this issue. We are suing Edgware and Spring 1.5.x and I noticed when I upgraded to Edgware.SR4 all the modules that connected to database started failing and upon couple of days of debugging found out that **org.springframework.cloud.service.common.RelationalServiceInfo** class had a recent change in 1.2.6.Release (works fine in 1.2.5.Release), where as part of url, User name and password are getting encoded and our password is also being encoded which happens to have a ! mark and wont connect thus.

Change was made in **formatUserinfo**() of that class.

Additional info (may be relavant)

We are connecting to external database from PCF using Userprovided service with a URI configured.

**Comment by spencergibb** [comment]
That class is located here https://github.com/spring-cloud/spring-cloud-connectors
