### ISSUE TITLE
Images are missing in spring cloud document

### ISSUE THREAD

**Issue by anbusampath** [spring-projects/spring-cloud#32]
https://cloud.spring.io/spring-cloud-static/Finchley.SR2/multi/multi__main_concepts.html

![image](https://user-images.githubusercontent.com/1268973/48803728-c5f63a80-ed38-11e8-983a-f7d1220c4609.png)

**Comment by ryanjbaxter** [comment]
I would report the issue here https://github.com/spring-cloud/spring-cloud-stream
