### ISSUE TITLE
BinderAwareChannelResolver: threadsaftey

### ISSUE THREAD

**Issue by robjwilkins** [spring-projects/spring-cloud#36]
I have found a problem with the BinderAwareChannelResolver and thread safety.

When using the BinderAwareChannelResolver to dynamically send to topics in a multi threaded environment, I have been having issues with the call throwing MessagingExceptions due to `Dispatcher has no subscribers for channel`.  The problems occur on the initial call to the topic

On digging through the code behind the BinderAwareChannelResolver I found it uses DynamicDestinationsBindable which is not thread safe.

I have worked around this problem by maintaining a `Set` of topics which have been called, and using a synchronised code block, to ensure the topic has been correctly bound before further calls are made to it.

**Comment by spencergibb** [comment]
If this is for spring cloud stream, please open in issue there.https://github.com/spring-cloud/spring-cloud-stream

**Comment by robjwilkins** [comment]
done: https://github.com/spring-cloud/spring-cloud-stream/issues/1570
