### ISSUE TITLE
Greenwich.RC2 Project link is not working

### ISSUE THREAD

**Issue by crimsonvspurple** [spring-projects/spring-cloud#37]
https://github.com/spring-projects/spring-cloud/wiki/Spring-Cloud-Greenwich-Release-Notes

![image](https://user-images.githubusercontent.com/11375716/51459802-e156e380-1d83-11e9-9503-f1b8f822954f.png)

**Comment by spencergibb** [comment]
Fixed

**Comment by crimsonvspurple** [comment]
Thank you.

Where can I see the issues being worked on/fixed for RC3/release?
