### ISSUE TITLE
Typo at https://spring.io/projects/spring-cloud

### ISSUE THREAD

**Issue by Macarse** [spring-projects/spring-cloud#53]
Sorry, I couldn't find the correct gh-page with the text to create a PR.

In  https://spring.io/projects/spring-cloud says:
```
Spring Cloud takes a very declarative approach, and often you get a lot of fetaures with just a classpath change and/or an annotation. 
```

`features` instead of `fetaures`

**Comment by ryanjbaxter** [comment]
Should be fixed now, thanks!
