### ISSUE TITLE
spring-cloud greenwich opentracing missing spans with spring boot 2.1.5

### ISSUE THREAD

**Issue by pstitt** [spring-projects/spring-cloud#55]
I have an issue with missing opentracing spans that only happens after upgrading from spring boot 2.1.4 to 2.1.5

The application has a rest controller that in turn uses webclient to call back to itself (to demonstrate the issue).

The expected trace is:
hello
  GET /world
    world
      sleep

With 2.1.5 the outcome is:
hello
  Get /world
sleep

Because the world controller span is missing, its child spans lose their context.

Attached is a project that demonstrates it working with spring boot 2.1.4 and the spans being logged to console.

Run with gradle bootRun and hit http://localhost:8080/hello

Update the spring boot version to 2.1.5 and repeat to see the "world" span is missing.

**Comment by pstitt** [comment]
Use this version to reproduce instead as it has a gradle wrapper and fixes an issue caused by the git gradle plugin.

[spring-cloud-tracing-bug.tar.gz](https://github.com/spring-projects/spring-cloud/files/3268411/spring-cloud-tracing-bug.tar.gz)

**Comment by spencergibb** [comment]
Please open the issue here https://github.com/spring-cloud/spring-cloud-sleuth
