### ISSUE TITLE
Spring Cloud integration with Google Cloud Run

### ISSUE THREAD

**Issue by wer-mathurin** [spring-projects/spring-cloud#57]

**Comment by spencergibb** [comment]
Maybe it should go here https://github.com/spring-cloud/spring-cloud-gcp/ and please be more specific as we have no idea with just a title.

**Comment by wer-mathurin** [comment]
Sorry, just hit the enter key by mistake before finishing the comment!

The use case is when we want to enable service-to-service security.  When Cloud Run is call from another service running inside kubernetes,  you must get a token before calling the service, like this:

`var receivingURL = "THE URL OF THE CLOUD RUN";` 
`var url = "http://metadata/computeMetadata/v1/instance/service-accounts/default/identity?audience=";`

`var token = client.build().get().uri(url+receivingURL).header("Metadata-Flavor", "Google").retrieve().bodyToMono(String.class);`
		
`var flux = token.flatMap( t -> client.build().get().uri(receivingURL).header("Authorization", "Bearer " + t).retrieve().bodyToMono(String.class));`

From a development perspective, we would like to use the DiscoveryClient wonderful capability but be able to configure adding the needed header only when running inside kubernetes

**Comment by spencergibb** [comment]
So maybe try in Spring Cloud kubernetes
