### ISSUE TITLE
Use @RestController On fallbackController

### ISSUE THREAD

**Issue by king-john** [spring-projects/spring-cloud#59]
when I use HystrixGatewayFilterFactory, create a FallbackController like this :

@RestController
@Slf4j
public class FallBackController {

	@RequestMapping("/fallback")
	public ResponseVO<VO> fallback() {
	     log.info("fallback");
	    return ResponseUtil.error(new VO());
	}
}

when Hystrix fallback response is as follows:
{
    "timestamp": "2019-09-16T09:50:39.147+0000",
    "path": "/notice/example/send_mq",
    "status": 504,
    "error": "Gateway Timeout",
    "message": "Response took longer than configured timeout"
}
why it is not my ResponseVO JSON?

**Comment by spencergibb** [comment]
I don't know. Please supply the version you are using and how you are configuring hystrix

**Comment by spencergibb** [comment]
Please open this issue in spring-cloud-netflix with the requested information
