### ISSUE TITLE
Sleuth and Redis will not work with deps to >Greenwich.RELEASE

### ISSUE THREAD

**Issue by ton3r** [spring-projects/spring-cloud#60]
I've an application which contains dependencies to both. Sleuth and Redis. When I start it up I've got 

```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call the method reactor.core.scheduler.Schedulers.setExecutorServiceDecorator(Ljava/lang/String;Ljava/util/function/BiFunction;)V but it does not exist. Its class, reactor.core.scheduler.Schedulers, is available from the following locations:

    jar:file:~/.m2/repository/io/projectreactor/reactor-core/3.2.2.RELEASE/reactor-core-3.2.2.RELEASE.jar!/reactor/core/scheduler/Schedulers.class

It was loaded from the following location:

    file:~/.m2/repository/io/projectreactor/reactor-core/3.2.2.RELEASE/reactor-core-3.2.2.RELEASE.jar
```

When I switch to `Greenwich.M3` everthings works fine. As far as I can see, uses the Sleuth deps only "optional" dependencies to reactor-core where Redis uses fixed versions.

I've got an demo SpringBoot app here -> https://github.com/ton3r/sleuth-reactor-test

`Greenwhich.RELEASE` is the last running Version with my example

**Comment by spencergibb** [comment]
Please file the issue here. https://github.com/spring-cloud/spring-cloud-sleuth

M3 is not supported since it is a milestone. Please update to Greenwich.SR3 and boot 2.1.8. If you still have an issue file at the above link.

**Comment by ton3r** [comment]
works perfect. Thanks
