### ISSUE TITLE
Problem using ribbon and rabbitMQ consumer with maxRetries

### ISSUE THREAD

**Issue by marlonmoncores** [spring-projects/spring-cloud#62]
When using this version of springcloud and also netflix-ribbon. The LoadBalancerAutoConfiguration creates a default RetryTemplate bean. The problem happens because that default bean gets injected into the RabbitMessageChannelBinder and its supperclass AbstractBinder ignore the queue consumer configuration, because of the injected retryTemplate (method: buildRetryTemplate). So it's impossible to configure queue specific retry policy.

Using decompiled source:
![image](https://user-images.githubusercontent.com/20006206/70632798-4ae71700-1c0e-11ea-8db7-7c464f98329f.png)

Here is my code:
https://bitbucket.org/marlonmoncores/rabbitmessagesenderandconsumererrorbenchmark/src/spring_cloud_Edgware.SR6_problem/

**Comment by spencergibb** [comment]
Unfortunately edgware is no longer supported. If you can upgrade to Greenwich or Hoxton and the problem persists please open a new issue in spring cloud commons
