### ISSUE TITLE
Support for Spring Boot 2.3.x

### ISSUE THREAD

**Issue by MarioKusek** [spring-projects/spring-cloud#68]
Is there a defined date or rough timeframe when the support for Spring Boot 2.3.x will be available? I didn't find any info about that.

**Comment by spencergibb** [comment]
It's documented here. Support was released last week in Hoxton.SR5 

https://github.com/spring-cloud/spring-cloud-release/wiki/Supported-Versions#supported-releases

**Comment by MarioKusek** [comment]
Tnx

**Comment by stovocor** [comment]
Please update the "Release Trains" section, too. Currently it looks like Hoxton does not support 2.3.x.

https://spring.io/projects/spring-cloud
