### ISSUE TITLE
starter-hystrix-dashboard compatibility error

### ISSUE THREAD

**Issue by weissxu** [spring-projects/spring-cloud#70]
<spring-cloud-alibaba.version>2.2.1.RELEASE</spring-cloud-alibaba.version>
    <spring-cloud.version>Hoxton.SR5</spring-cloud.version>
    <hystrix-dashboard.version>2.2.3.RELEASE</hystrix-dashboard.version>

detail for this, follow: http://www.yusiwei.top/article/1591705598

**Comment by spencergibb** [comment]
Please provide the work m error and steps to reproduce here

**Comment by spencergibb** [comment]
Please open an issue with the error and steps to reproduce in spring cloud Netflix
