### ISSUE TITLE
please update hystrix monitor js code use :  $(window).ready(), not use $(window).load

### ISSUE THREAD

**Issue by startjava** [spring-projects/spring-cloud#71]
http://localhost:18000/actuator/hystrix.stream

ping: 

data: {"type":"HystrixCommand","name":"TestController1Client#test_Error2(HttpServletRequest,HttpServletResponse)","group":"Provider","currentTime":1595392539063,"isCircuitBreakerOpen":true,"errorPercentage":0,"errorCount":0,"requestCount":0,"rollingCountBadRequests":0,"rollingCountCollapsedRequests":0,"rollingCountEmit":0,"rollingCountExceptionsThrown":0,"rollingCountFailure":0,"rollingCountFallbackEmit":0,"rollingCountFallbackFailure":0,"rollingCountFallbackMissing":0,"rollingCountFallbackRejection":0,"rollingCountFallbackSuccess":0,"rollingCountResponsesFromCache":0,"rollingCountSemaphoreRejected":0,"rollingCountShortCircuited":0,"rollingCountSuccess":0,"rollingCountThreadPoolRejected":0,"rollingCountTimeout":0,"currentConcurrentExecutionCount":0,"rollingMaxConcurrentExecutionCount":0,"latencyExecute_mean":0,"latencyExecute":{"0":0,"25":0,"50":0,"75":0,"90":0,"95":0,"99":0,"99.5":0,"100":0},"latencyTotal_mean":0,"latencyTotal":{"0":0,"25":0,"50":0,"75":0,"90":0,"95":0,"99":0,"99.5":0,"100":0},"propertyValue_circuitBreakerRequestVolumeThreshold":20,"propertyValue_circuitBreakerSleepWindowInMilliseconds":5000,"propertyValue_circuitBreakerErrorThresholdPercentage":50,"propertyValue_circuitBreakerForceOpen":false,"propertyValue_circuitBreakerForceClosed":false,"propertyValue_circuitBreakerEnabled":true,"propertyValue_executionIsolationStrategy":"THREAD","propertyValue_executionIsolationThreadTimeoutInMilliseconds":3000,"propertyValue_executionTimeoutInMilliseconds":3000,"propertyValue_executionIsolationThreadInterruptOnTimeout":true,"propertyValue_executionIsolationThreadPoolKeyOverride":null,"propertyValue_executionIsolationSemaphoreMaxConcurrentRequests":10,"propertyValue_fallbackIsolationSemaphoreMaxConcurrentRequests":10,"propertyValue_metricsRollingStatisticalWindowInMilliseconds":10000,"propertyValue_requestCacheEnabled":true,"propertyValue_requestLogEnabled":true,"reportingHosts":1,"threadPool":"Provider"}

data: {"type":"HystrixThreadPool","name":"Provider","currentTime":1595392539063,"currentActiveCount":0,"currentCompletedTaskCount":46,"currentCorePoolSize":10,"currentLargestPoolSize":10,"currentMaximumPoolSize":10,"currentPoolSize":10,"currentQueueSize":0,"currentTaskCount":46,"rollingCountThreadsExecuted":0,"rollingMaxActiveThreads":0,"rollingCountCommandRejections":0,"propertyValue_queueSizeRejectionThreshold":5,"propertyValue_metricsRollingStatisticalWindowInMilliseconds":10000,"reportingHosts":1}

ping: 

-----------------------------------------------------------------------------
http://localhost:19000/hystrix/monitor?stream=http%3A%2F%2Flocalhost%3A18000%2Factuator%2Fhystrix.stream&delay=1000

show double loading
-----------------------------------------------------------------------------
chrome F12 show:
jquery.min.js:2 Uncaught TypeError: e.indexOf is not a function
    at k.fn.init.k.fn.load (jquery.min.js:2)
    at monitor?stream=http%3A%2F%2Flocalhost%3A18000%2Factuator%2Fhystrix.stream&delay=1000:110
-------------------------------------------------------------------------------
i look webjar jquery version :
jquery 3.4.1 
-------------------------------------------------------------------------------
please replace js code:
$(window).load

replace bottom:

$(window).ready
--------------------------------------------------------------------------------
load method() Deprecated ！！！

**Comment by startjava** [comment]
chrome version:84.0.4147.89

**Comment by spencergibb** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-netflix/pull/3817

**Comment by startjava** [comment]
@spencergibb   but my spring-cloud use which version ?? i now use H.sr6，，

**Comment by spencergibb** [comment]
It hasn't been released yet, it will be in Hoxton.SR7
