### ISSUE TITLE
Kafka not working after upgrading to Hoxton.SR9

### ISSUE THREAD

**Issue by aariza1** [spring-projects/spring-cloud#75]
Hello, 
I have been getting the following exception in all our services that include Kafka after upgrading to Hoxton.SR9.
With Hoxton.SR8 is working just fine.

`org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageDeliveryException: `

We are also using Spring Boot 2.3.6.RELEASE
Any idea what could be triggering this error?

Thank you in advance!

**Comment by spencergibb** [comment]
Please open in the spring kafka project
