### ISSUE TITLE
Have a compatible version of Spring cloud for the Spring Boot 2.4.0 release

### ISSUE THREAD

**Issue by piyushmor** [spring-projects/spring-cloud#77]
Currently Hoxton is not compatible with Spring Boot 2.4.0. I have been made aware that it will never be. Thus, I would like to know when we can have a Spring cloud version that works for the latest Spring Boot.

**Comment by ryanjbaxter** [comment]
Spring Cloud 2020.0.0 will be compatible with Boot 2.4.0.  Tentative release schedule can be found here https://github.com/spring-cloud/spring-cloud-release/milestones
