### ISSUE TITLE
Q: server.port within container

### ISSUE THREAD

**Issue by torsten-liermann** [spring-projects/spring-cloud#8]
Hi,

The use of @EnableEurekaServer within a container (e.g. Tomcat) is probably not intended, but nevertheless it is a valid usecase for us and we need it.
We have a problem with the definition of server.port in the default zone in the form that in the url

http://localhost:${server.port}/eureka/

the server.port is not being set via spring. Is there an elegant solution to this? Should this port be set from the container (tomcat, jetty, glassfish) or should the Eureka configuration be stored in the config service?

Thanks!
Torsten

**Comment by spencergibb** [comment]
Running as a war limits what we can do.  I'm a bit confused, though.  Is your problem running the server?  or having clients connect to eureka?

**Comment by torsten-liermann** [comment]
yes, it's the default zone configuration within the server.

**Comment by spencergibb** [comment]
@torsten-liermann just realized, this is in the wrong tracker, can you create a new issue in https://github.com/spring-cloud/spring-cloud-netflix/issues
