### ISSUE TITLE
Application not start when zipkin is disabled by environment variable - 2020.0.0

### ISSUE THREAD

**Issue by kubav182** [spring-projects/spring-cloud#80]
I have dependency org.springframework.cloud:spring-cloud-sleuth-zipkin from spring cloud version 2020.0.0
There was not this problem in previous version Hoxton.SRX.

In application properties:
spring.zipkin.enabled=false
spring.zipkin.base-url=http://zipkin:9411
spring.sleuth.sampler.probability=1.0

Sometimes I want to turn on zipkin so I have environment variable in docker deployment
SPRING_ZIPKIN_ENABLED='false' // I switch to true if needed

When I start application with false value in env var I get this error, but when I remove this env var completely it starts fine:
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 3 of method traceFunctionAroundWrapper in org.springframework.cloud.sleuth.autoconfig.instrument.messaging.TraceFunctionAutoConfiguration required a bean of type 'org.springframework.cloud.sleuth.propagation.Propagator$Setter' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=false)

Action:

Consider defining a bean of type 'org.springframework.cloud.sleuth.propagation.Propagator$Setter' in your configuration.

**Comment by spencergibb** [comment]
Please open this in the spring Cloud sleuth issue tracker https://github.com/spring-cloud/spring-cloud-sleuth/issues

**Comment by kubav182** [comment]
ok it is tracked in https://github.com/spring-cloud/spring-cloud-sleuth/issues/1813
